[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
regex = "1.10"
rustrict = "0.7.5"
rand = "0.8.5"
log = "0.4"
once_cell = "1.18.0"